# Generated by Django 4.1.3 on 2022-11-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakecakeapp', '0003_alter_ingredient_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='levels',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shape',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('LV', 'Уровни'), ('SH', 'Форма'), ('TP', 'Топпинг'), ('BR', 'Ягоды'), ('DC', 'Декор')], db_index=True, max_length=2, verbose_name='Тип'),
        ),
    ]
