# Generated by Django 4.1.3 on 2022-11-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakecakeapp', '0004_remove_order_levels_remove_order_shape_and_more'),
    ]

    def add_ingredients(apps, schema_editor):
        Ingredient = apps.get_model('bakecakeapp', 'Ingredient')
        Ingredient.objects.bulk_create([
            Ingredient(type="LV", name="1 уровень", price=400),
            Ingredient(type="LV", name="2 уровня", price=750),
            Ingredient(type="LV", name="3 уровня", price=1100),

            Ingredient(type="SH", name="Квадрат", price=600),
            Ingredient(type="SH", name="Круг", price=400),
            Ingredient(type="SH", name="Прямоугольник", price=1000),

            Ingredient(type="TP", name="Без", price=0),
            Ingredient(type="TP", name="Белый соус", price=200),
            Ingredient(type="TP", name="Карамельный сироп", price=180),
            Ingredient(type="TP", name="Кленовый сироп", price=200),
            Ingredient(type="TP", name="Клубничный сироп", price=300),
            Ingredient(type="TP", name="Черничный сироп", price=350),
            Ingredient(type="TP", name="Молочный шоколад", price=200),

            Ingredient(type="BR", name="Ежевика", price=400),
            Ingredient(type="BR", name="Малина", price=300),
            Ingredient(type="BR", name="Голубика", price=450),
            Ingredient(type="BR", name="Клубника", price=500),

            Ingredient(type="DC", name="Фисташки", price=300),
            Ingredient(type="DC", name="Безе", price=400),
            Ingredient(type="DC", name="Фундук", price=30),
            Ingredient(type="DC", name="Пекан", price=30),
            Ingredient(type="DC", name="Маршмеллоу", price=200),
            Ingredient(type="DC", name="Марципан", price=280)
            
        ])

    operations = [
        migrations.RunPython(add_ingredients),
    ]
