# Generated by Django 4.1.3 on 2022-11-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakecakeapp', '0005_auto_20221124_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(db_index=True, max_length=40, null=True, verbose_name='id_платежа'),
        ),
    ]
