# Generated by Django 4.1.3 on 2022-11-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utm_tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utmvisit',
            name='content',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
